export const packageName = "@pickforge/picklab-android";

export {
  commonSdkPaths,
  detectAndroidEnvironment,
  detectKvm,
  detectSdkRoot,
  detectSdkTools,
  findSdkTool,
  isValidSystemImageId,
  listSystemImages,
  missingSdkMessage,
  resolveSdkRoot,
  sdkmanagerInstallCommand,
  systemImageInstalled,
  type AndroidEnvironment,
  type DetectSdkRootOptions,
  type KvmStatus,
  type SdkToolName,
  type SdkToolPaths,
  type SystemImage,
} from "./sdk.js";

export {
  avdHomeDir,
  buildCreateAvdArgs,
  createAvd,
  DEFAULT_AVD_NAME,
  listAvds,
  parseEmulatorListAvds,
  scanAvdHome,
  type CreateAvdArgsOptions,
  type CreateAvdOptions,
  type CreateAvdResult,
  type ListAvdsOptions,
} from "./avd.js";

export {
  assertConsolePort,
  buildEmulatorArgs,
  consolePortLockPath,
  emulatorSerial,
  MAX_CONSOLE_PORT,
  MIN_CONSOLE_PORT,
  pickConsolePort,
  releaseConsolePort,
  startEmulator,
  stopEmulator,
  tryReserveConsolePort,
  waitForBoot,
  type EmulatorArgsOptions,
  type EmulatorHandle,
  type StartEmulatorOptions,
  type StopEmulatorOptions,
  type WaitForBootOptions,
} from "./emulator.js";

export {
  back,
  buildClearLogcatArgs,
  buildInstallApkArgs,
  buildKeyeventArgs,
  buildLaunchAppArgs,
  buildLogcatArgs,
  buildScreenshotArgs,
  buildTapArgs,
  buildTypeTextArgs,
  buildUiCatArgs,
  buildUiCleanupArgs,
  buildUiDumpArgs,
  clearLogcat,
  escapeInputText,
  getUiTree,
  home,
  installApk,
  KEYCODE_BACK,
  KEYCODE_HOME,
  launchApp,
  listDevices,
  logcat,
  parseAdbDevices,
  pressKey,
  resolveAdb,
  runAdb,
  screenshot,
  splitInputText,
  tap,
  typeText,
  UI_DUMP_REMOTE_PATH,
  type AdbDevice,
  type AdbTargetOptions,
  type GetUiTreeOptions,
  type LogcatArgsOptions,
} from "./adb.js";

export {
  androidSessionLogDir,
  createAndroidSession,
  destroyAndroidSession,
  getAndroidSessionStatus,
  type AndroidSessionHandle,
  type AndroidSessionOpOptions,
  type AndroidSessionStatus,
  type CreateAndroidSessionOptions,
} from "./session.js";

export { findOnPath } from "./util.js";
