export const packageName = "@pickforge/picklab-core";

export {
  agentsDir,
  ensureDir,
  globalConfigPath,
  isProfileConfined,
  picklabHome,
  projectConfigPath,
  runsDir,
  sessionsDir,
  type EnvLike,
} from "./paths.js";

export {
  deepMerge,
  isEvidenceEnabled,
  loadConfig,
  readConfigFile,
  resolvedDefaults,
  saveGlobalConfig,
  saveProjectConfig,
  type PicklabConfig,
  type PicklabProfile,
  type ViewerMode,
} from "./config.js";

export {
  createRun,
  EVIDENCE_ACTION_LOG,
  EVIDENCE_VERSION,
  listRuns,
  RunHandle,
  type ArtifactType,
  type CreateRunOptions,
  type RunArtifact,
  type RunManifest,
  type RunStatus,
} from "./run.js";

export {
  activePointerPath,
  appendAction,
  beginEvidenceRun,
  clearActivePointer,
  EVIDENCE_MAX_BYTES,
  EVIDENCE_MAX_LINE_BYTES,
  EVIDENCE_RETENTION_KEEP,
  isEvidenceRun,
  isEvidenceTruncated,
  isTruncationRecord,
  pruneFinalizedEvidenceRuns,
  readActions,
  resolveActivePointer,
  type ActiveEvidenceClaim,
  type ActiveEvidencePointer,
  type AppendActionOptions,
  type AppendOutcome,
  type AppendResult,
  type BeginEvidenceRunOptions,
  type BeginEvidenceRunResult,
  type EvidenceAction,
  type EvidenceActionStatus,
  type EvidenceRecord,
  type EvidenceTruncationRecord,
  type PointerResolution,
  type PruneEvidenceOptions,
} from "./evidence.js";

export { isSecretKey, redactEnv, redactSecrets } from "./redact.js";

export {
  MAX_ERROR_TEXT_LENGTH,
  sanitizeActionTarget,
  sanitizeErrorText,
  sanitizeNetworkFailure,
  sanitizeTypedValue,
  sanitizeUrlForEvidence,
  type SanitizedActionTarget,
  type SanitizedHttpMethod,
  type SanitizedNetworkFailure,
  type SanitizedResourceType,
  type SanitizedTypedValue,
  type TypedInputType,
} from "./evidence-sanitize.js";

export {
  CommandError,
  isPidAlive,
  listProcessGroupMembers,
  processIdentityMatches,
  readProcessIdentity,
  readProcessStartTicks,
  runCommand,
  startDaemon,
  stopPid,
  stopProcessGroupVerified,
  type DaemonHandle,
  type OwnedDaemonHandle,
  type ProcessIdentity,
  type RunCommandOptions,
  type RunCommandResult,
  type StartDaemonOptions,
  type StopProcessGroupOutcome,
  type StopProcessGroupResult,
} from "./proc.js";

export {
  captureToTarget,
  requireDisplay,
  resolveDesktopCapableSession,
  resolveRunnableSession,
  resolveScreenshotTarget,
  sessionHasCapability,
  type ResolveDesktopCapableSessionOptions,
  type ResolveRunnableSessionOptions,
  type ResolveScreenshotTargetOptions,
  type RunnableSessionType,
  type ScreenshotTarget,
  type SessionCapability,
} from "./target.js";

export {
  REAPER_CLEANUP_PENDING_META_KEY,
  createSession,
  destroySessionRecord,
  getSession,
  isDisplaySocketAlive,
  isSessionProcessAlive,
  listSessions,
  reapDeadRunningSessions,
  updateSession,
  type AndroidSessionInfo,
  type BrowserSessionInfo,
  type CreateSessionInput,
  type DesktopSessionInfo,
  type SessionLivenessCheck,
  type SessionRecord,
  type SessionStatus,
  type SessionType,
} from "./session.js";
